All perpose flour (1&1/2cup)
Milk poewder 3 (tbsp)
salt
instant yeast (1 tsp)
sugar(1 tsp)
oil (3 tbsp)
warmwater about 1/2 cup
plastic foil
sausce
cheese
baby corn
capsicum
red bell paper
jelpeno 
olives
marjoram
 basil
 garlick poewder
parmesan cheese
sprinkel it all on the top of the pizza
now the pizza and put it in oven until it get golden brown
pre heat the oven for 225°C 
time is like 13 to 17 min